### ISSUE TITLE
Attempting to run

### ISSUE THREAD

**Issue by rsoric** [alameda-project/matorral#105]
Hi!

Cool project, I'm attempting to run it locally for a demonstration. I have installed a venv using conda with Python 3.7 as it says in the instructions, but it won't install the requirements, as Django 4.x is only for Python 3.8 and up. When i tried Python 3.8, then it wouldn't install some other component of Django:

```
Collecting django-admin-list-filter-dropdown==1.0.2 (from -r requirements\base.t
xt (line 34))
  Downloading django_admin_list_filter_dropdown-1.0.2-py3-none-any.whl (3.8 kB)
ERROR: Ignored the following versions that require a different python version: 5
.0 Requires-Python >=3.10; 5.0.1 Requires-Python >=3.10; 5.0a1 Requires-Python >
=3.10; 5.0b1 Requires-Python >=3.10; 5.0rc1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement django-comments-x
td-2.9.8 (from versions: none)
ERROR: No matching distribution found for django-comments-xtd-2.9.8

Process finished with exit code 1.
```

Could you help me out with getting started? Any help is appreciated.

-Rob

**Comment by matagus** [comment]
Hi there!

Apologies that I didn't see this message until now :/ I'm going to upgrade this project to use the latest version of Django, Celery, etc in the next days. I'll also include a Docker file to run it. I'll keep you posted.

**Comment by rsoric** [comment]
Hey! Don't worry, I needed to make an app like this pretty urgently and used your screenshots for inspiration and wrote a little thing myself which was sufficient. I don't really need to run the app anymore, the project was completed. Thank you anyways, I still appreciate the reply. 

-Rob
